export type AccountType = 'cash' | 'bank' | 'credit' | 'savings';
export type TransactionType = 'income' | 'expense' | 'transfer';
export type CategoryType = 'income' | 'expense' | 'transfer';

export const ACCOUNT_TYPE_LABEL: Record<AccountType, string> = {
  cash: 'Tunai',
  bank: 'Bank',
  credit: 'Kartu Kredit',
  savings: 'Tabungan',
};

// §13: which authors' rows the user wants to see in lists.
export type ViewerScope = 'mine' | 'others' | 'all';

export interface Profile {
  id: string;
  name: string;
  currency_code: string;
  created_at: string;
  updated_at: string;
}

// §13: an invited member belongs to a host's group. PK = (host, member).
// `host` / `member` Profile pointers are hydrated by service-layer joins
// for display in the Profile page lists.
export interface GroupMembership {
  host_user_id: string;
  member_user_id: string;
  joined_at: string;
  host?: Profile;
  member?: Profile;
}

export type GroupInvitationStatus =
  | 'pending'
  | 'accepted'
  | 'revoked'
  | 'expired';

export interface GroupInvitation {
  id: number;
  host_user_id: string;
  invitee_email: string;
  token: string;
  status: GroupInvitationStatus;
  created_at: string;
  expires_at?: string | null;
  accepted_at?: string | null;
}

export interface Account {
  id: number;
  user_id: string;          // group owner
  created_by: string;       // author (§13)
  name: string;
  type: AccountType;
  balance: number;
  currency_code: string;
  color?: string;
  deleted_at?: string | null;
  credit_limit?: number;
  statement_day?: number;
  payment_due_day?: number;
  created_at: string;
  created_by_user?: Profile;
}

export interface AccountBalance extends Account {
  total_reserved: number;
  available_balance: number;
}

export interface Category {
  id: number;
  user_id: string | null;     // NULL = system default
  created_by: string | null;  // NULL = system default; else author (§13)
  name: string;
  type: CategoryType;
  icon?: string;
  color?: string;
  parent_id?: number;
  created_by_user?: Profile;
}

export interface Transaction {
  id: number;
  user_id: string;            // group owner
  created_by: string;         // author (§13)
  account_id: number;
  category_id?: number;       // NULL when items[] is non-empty (see §7.6)
  amount: number;             // equals SUM(items.amount) at create/update time
  type: TransactionType;
  date: string;
  note?: string;
  reserved_from_account_id?: number;
  settlement_id?: number;
  parent_tx_id?: number;
  transfer_pair_id?: number;
  // Set on transfer rows generated by a settlement payoff (all legs, incl. the
  // conduit's second leg) so reverseSettlement can find + delete them (§7.4.3).
  settlement_transfer_id?: number | null;
  sort_index?: number;          // DB NOT NULL; optional at write time (service defaults to Date.now())
  created_at: string;
  category?: Category;
  account?: Account;
  reserved_from_account?: Account;
  created_by_user?: Profile;
  items?: TransactionItem[];
}

export interface TransactionItem {
  id: number;
  transaction_id: number;
  created_by: string;         // author (§13)
  category_id?: number;
  amount: number;
  note?: string;
  position: number;
  // per-item reservation (§7.3 hybrid invariant, §7.6)
  reserved_from_account_id?: number;
  settlement_id?: number;
  parent_item_id?: number;
  created_at: string;
  category?: Category;
  reserved_from_account?: Account;
}

// One unsettled reservation entry — either a parent-level reservation
// (items absent) or an item-level reservation (items present).
export interface ReservationEntry {
  kind: 'parent' | 'item';
  id: number;
  amount: number;
  parent: Transaction;
  category?: Category;
  note?: string;
}

export interface DebtSettlement {
  id: number;
  transfer_tx_id?: number;
  user_id: string;            // group owner (= lender account.user_id)
  created_by: string;         // author (§13)
  account_id: number;
  reserved_from_account_id: number;
  total_amount: number;
  settled_at: string;
}

export interface Tag {
  id: number;
  user_id: string;
  name: string;
}

// §14 Statistics — one row of the expense-by-category breakdown.
// `category` is null for the synthetic "Tanpa kategori" bucket.
// `total` is summed across both parent-level (no items) and item-level rows.
// `share` is total / sumOfAllTotals, computed by the service so the page just renders.
export interface CategoryBreakdownEntry {
  category: Category | null;
  total: number;
  count: number;
  share: number;
}

// §14 Statistics — one contribution that fed a category bucket. Returned by
// TransactionService.getTransactionsForCategory when the user drills into a
// breakdown row. Sourced from a parent (no items) or one item within a split
// transaction; `contribution` is the slice that fed the bucket (parent.amount
// or item.amount). `transaction` is always the parent row for display context.
export interface CategoryDrillEntry {
  transaction: Transaction;
  contribution: number;
  source: 'parent' | 'item';
  itemId?: number;
  itemNote?: string | null;
}

// §14 Statistics — one row of the current-state reservation summary.
// Grouped by `reserved_from_account_id` (the owing account).
// `totalReserved` matches `account_balances.total_reserved` for that account
// modulo viewer-scope filtering.
export interface ReservationSummaryEntry {
  account: Account;
  totalReserved: number;
  count: number;
  oldestDate: string;
}

// Calculator Hutang picker — one unsettled-debt relationship: how much the
// `owing` account owes the `creditor` (the payer that fronted the money,
// = `account_id` on the reservation). Sums parent- + item-level reservations
// for that (owing → creditor) pair. Honors viewer scope.
export interface ReservationPairEntry {
  owing: Account;
  creditor: Account;
  totalReserved: number;
  count: number;
}

// One row extracted from a bank screenshot, awaiting user review (see §9 Transaction Import).
// `note` is prefilled with the LLM's cleaned-up label and is user-editable — it becomes
// the saved transaction's `note` column verbatim. `rawDescription` is the verbatim text
// from the screenshot, kept around as read-only "Asli" reference in the review UI.
// For type='transfer', `transferDirection` is set by the LLM from the screenshot's sign:
//   'out' → money left the picked account (picked = from, user picks `to`)
//   'in'  → money entered the picked account (picked = to,   user picks `from`)
// `transferAccountId` is the user's selection of the other side at review time.
export interface ImportDraft {
  // `null` when the extractor could not determine the date from the screenshot —
  // the user must pick a date in Step 4 before commit (canCommit gates on this).
  date: string | null;
  amount: number;
  type: 'income' | 'expense' | 'transfer';
  rawDescription: string;
  note?: string;
  suggestedCategoryId?: number;
  transferDirection?: 'in' | 'out';
  transferAccountId?: number;
  // Reservation owing account for expense rows (Flavor A when payer is credit,
  // Flavor B otherwise). null/undefined = no reservation. Forced null on
  // non-expense rows by the UI. The bulk picker at the top of the Review step
  // seeds this on all expense rows; each row also has its own override picker.
  reservedFromAccountId?: number | null;
  skip: boolean;
}
