/* eslint-disable */
// AUTOGENERATED tooling — see CLAUDE.md §10.
// Reads SUPABASE_URL / SUPABASE_ANON_KEY from process.env (loading .env if present)
// and writes src/environments/environment.{ts,prod.ts}. Both outputs are gitignored.

const fs = require('fs');
const path = require('path');

try {
  require('dotenv').config();
} catch (_) {
  // dotenv is optional in CI where env vars come from the platform.
}

const { SUPABASE_URL, SUPABASE_ANON_KEY } = process.env;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    '[generate-env] Missing SUPABASE_URL or SUPABASE_ANON_KEY.\n' +
      '  Local dev:  copy .env.example to .env and fill it in.\n' +
      '  CI/Vercel:  set both vars in the project environment.',
  );
  process.exit(1);
}

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(envDir, { recursive: true });

const render = (production) =>
  `// AUTOGENERATED by scripts/generate-env.js — do not edit by hand.
export const environment = {
  production: ${production},
  supabaseUrl: ${JSON.stringify(SUPABASE_URL)},
  supabaseKey: ${JSON.stringify(SUPABASE_ANON_KEY)},
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), render(false));
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), render(true));

console.log('[generate-env] wrote src/environments/environment.{ts,prod.ts}');
